[sheet]
sheet-name = Department

[database]
table-name = tbl_department

[module]
name = admin_department

[excel-to-database-mapping]
; column-count = 3
Unit = unit
Department = department
Code = code
Status = status

[template]
file = department-template.xlsx

[template-columns]
0 = Unit
1 = Department
2 = Code
3 = Status

[column-query-mapping]
Status = "SELECT status FROM tbl_status WHERE module = 'GEN'"
