[sheet]
sheet-name = MasterList

[database]
table-name = tbl_employee

[module]
name = employee

[excel-to-database-mapping]
Emp Code = old_emp_code
First Name = f_name
Last Name = l_name
; Display Name = display_name
Emp Status = emp_status
Emp Type = emp_type
off_loc_id = office_location_id
DOJ = doj
DOB = dob
UAN = uan
AADHAR = aadhar
PAN NO = pan_no
ESI NO = esi_no
BANK NAME = bank_name
ACCOUNT NO = bank_account_no
IFSC CODE = ifsc_code
M365 = m365
M365_Email = email
Personal_Add1 = add1
Personal_Add2 = add2
Personal_Email = personal_email
city_id = city
state_id = state
country_id = country
dept_id = department
desig_id = designation
entity_id = entity
Personal_Pin = pincode
entity_id = entity_id


[date-columns]
DOB = dob
DOJ = doj


[template]
file = employee-template.xlsx

[template-columns]
; Add the template columns (refer to the excel-to-database-mapping section for mapping)
0 = EMP CODE
1 = First Name
2 = Last Name
3 = Display Name
4 = EMP STATUS
5 = EMP Type
6 = Location
7 = DOJ
8 = DOB
9 = UAN
10 = AADHAR
11 = "PAN NO"
12 = "ESI NO"
13 = BANK NAME
14 = "ACCOUNT NO"
15 = IFSC CODE
16 = M365
17 = EMAIL
18 = Personal_Add1
19 = Personal_Add2
20 = city_id
21 = state_id
22 = country_id
23 = dept_id
24 = desig_id
25 = entity_id
26 = Pincode

[column-query-mapping]
ENTITY = "SELECT entity_code FROM tbl_entity"
EMPLOYEE TYPE = "SELECT 'Regular' AS emp_type UNION ALL SELECT 'Non-Regular' AS emp_type"
M365 = "SELECT 'YES' AS m365 UNION ALL SELECT 'NO' AS m365"
EMPLOYEE STATUS = "SELECT status FROM tbl_status WHERE module = 'GEN'"
LOCATION = "SELECT city FROM tbl_city"
DEPARTMENT = "SELECT name FROM tbl_department"
DESIGNATION = "SELECT name FROM tbl_designation"


